### ISSUE TITLE
docs: add an array rule example

### ISSUE THREAD

**Issue by hugosenari** [openpeep/nyml#2]
Hi, I really liked your rule/validation syntax.

Would be useful, include an array example to readme.

**Comment by georgelemon** [comment]
Not implemented yet, but I'm thinking at something like this

```yaml
name: "Matilda"
shop_list: 
    - "Apples"
    - "Bananas"
    - "Carrot juice"
    - "Beers"
    - "Soda"
```

```nim
rules = @[
    "name*:string",
    
    # 5 maximum length, only string
    "mylist*:array[5, string]",

    # no maximum length, only string
    "mylist*:array[string]",

    # no maximum length, only strings and integers
    "mylist*:array[string, int]",

    # or, mixed values, with or without a max length
    "mylist*:array[mixed]"
]
```

**Comment by hugosenari** [comment]
**Disclaimer:** bikeshedding ahead :bike:

Madam README say:
```
"name*:string(min = 8, max = 48)" 
```
Maybe, for interoperation consistency :thinking: 
```
"names*:array[string](min = 8, max = 48)" 
```


---

Sorry, random questions just because I liked your rule syntax simplicity :-)

Anywhere you borrow inspiration from?
Any plans to make it a lib to validate JsonNode (without parser) to apply in other projects (ie. in Madam)? 
Or Nyml will be that lib?

**Comment by georgelemon** [comment]
Thanks! Yes, you right. The validator should be a standalone library and single binary app, so it can be used from other programming languages, specially Node (in order to make Nim more... popular).

Madam readme needs a refresh. The idea started from Madam, where I had to create a human readable file for creating routes, middlewares. This is still work in progress on Madam repo.

On POST routes you will be able to instruct Madam what kind of data to expect, by field identifiers, data type, etc. This data will be received, of course via web requests. But here is a different validator that should be done on Madam side which should be triggerable from Nyml by using a magic caller `@`.

```yml
contact:
    fields:
        name: @madam.form.validator(text, required)
        email: @madam.form.validator(email)
        # ...
``` 

Another cool example, is
```yml
api:
    user: @madam.yallfake.user.profile(name, email, phone, address)
```

Which in Madam is going to be used to create a route for `/api/user` and return a JSON response by triggering a future component, called Yallfake. A faker, that can generate data based on given fields.

This has nothing to do with Nyml, the only thing is that it should be a `@` handler in Nyml that can make dynamic calls to some public Nim procedures.

P.S. Yallfake should be a separate library, too

L.E. I just discovered  @jiro4989 [faker library](https://github.com/jiro4989/faker). So I think this will be used instead 🤟

**Comment by hugosenari** [comment]
+1 for [Parrot](https://github.com/openpeep/parrot) :+1: 

Talking about `so it can be used from other programming languages`, have you considered [Genny](https://github.com/treeform/genny)?
To me fair, I hate compiled packages for [Node](https://stackoverflow.com/questions/49938066/compiling-node-sass-takes-10-minutes) or [Python](https://github.com/python-poetry/poetry/issues/3661), is always a pain to deal with version or wait compilation
So I would prefer your current solution or something like IPC/RPC (msgpack maybe) :thinking:
